import {
  BarChart3,
  Bell,
  Boxes,
  Clapperboard,
  ClipboardCheck,
  FileClock,
  Fish,
  Heart,
  Image,
  LayoutDashboard,
  LifeBuoy,
  List,
  MapPin,
  Megaphone,
  MessageSquareWarning,
  Package,
  RotateCcw,
  ScrollText,
  Settings,
  Shield,
  ShoppingCart,
  SlidersHorizontal,
  Store,
  Tag,
  Truck,
  UserCheck,
  Users,
  Wallet,
  Warehouse,
} from "lucide-react";

export const dashboardIcons = {
  BarChart3, Bell, Boxes, Clapperboard, ClipboardCheck, FileClock, Fish,
  Heart, Image, LayoutDashboard, LifeBuoy, List, MapPin, Megaphone,
  MessageSquareWarning, Package, RotateCcw, ScrollText, Settings, Shield,
  ShoppingCart, SlidersHorizontal, Store, Tag, Truck, UserCheck, Users,
  Wallet, Warehouse,
} as const;
