import { fishImages } from "@/components/landing/landing-data";
import { MarketPageHeader, MarketSection, SectionTitle } from "@/components/marketplace/page-shell";
import { ArrowRight, BadgeCheck, FileCheck2, MapPinned, Scale, ShieldCheck, Store, Truck } from "lucide-react";
import Image from "next/image";
import Link from "next/link";

export function AboutPage() {
  return <>
    <MarketPageHeader eyebrow="Why Machh Bazar" title="A fish market built around evidence" description="We make source, time, weight, handling, and seller performance visible so a fresh-fish purchase requires less guesswork." breadcrumbs={[{ label: "About" }]} />
    <MarketSection className="grid gap-4 py-8 lg:grid-cols-[1.2fr_0.8fr] lg:py-12"><div className="relative min-h-[420px] overflow-hidden rounded-lg"><Image src={fishImages.market} alt="Fresh fish prepared for clear marketplace inspection" fill priority sizes="(max-width: 1024px) 100vw, 60vw" className="object-cover" /></div><div className="relative min-h-[320px] overflow-hidden rounded-lg bg-market-rail p-7 text-market-rail-ink sm:p-9"><div className="landing-grid-dark pointer-events-none absolute inset-0 opacity-35" /><div className="relative"><p className="text-[10px] font-bold text-market-aqua uppercase">Our operating idea</p><p className="mt-5 font-heading text-4xl leading-[1.02] font-semibold">Freshness is not a slogan. It is a sequence of records.</p><p className="mt-6 text-sm leading-7 text-market-rail-ink/65">A trustworthy market should show where a lot came from, when it was handled, what it weighed, and who was responsible at each step.</p></div></div></MarketSection>
    <MarketSection className="py-16 sm:py-20"><SectionTitle eyebrow="Product principles" title="Local, practical, and data-transparent" /><div className="mt-8 grid gap-px overflow-hidden rounded-lg border border-border bg-border md:grid-cols-3">{[{ icon: MapPinned, title: "Source before story", text: "Origin and catch records appear before marketing claims." }, { icon: Scale, title: "Weight stays visible", text: "Requested, packed, and invoiced weight remain connected." }, { icon: FileCheck2, title: "Corrections stay public", text: "Trace events are appended, never silently rewritten." }].map(({ icon: Icon, title, text }) => <article key={title} className="bg-surface p-6"><Icon className="size-5 text-primary" /><h2 className="mt-6 font-heading text-2xl font-semibold text-ink">{title}</h2><p className="mt-3 text-xs leading-5 text-muted-foreground">{text}</p></article>)}</div></MarketSection>
    <div className="border-y border-border bg-surface"><MarketSection className="grid gap-12 py-16 lg:grid-cols-[0.8fr_1.2fr] lg:py-20"><SectionTitle eyebrow="Marketplace model" title="Trust is shared across the chain" description="Sellers, inspectors, operations staff, and customers each see the records needed for their decision—without exposing private KYC or payment data." /><div className="border-t border-border">{[{ icon: Store, label: "Verified sellers", text: "Publish active lots and fulfillment performance." }, { icon: BadgeCheck, label: "Evidence review", text: "Checks support freshness and source claims." }, { icon: Truck, label: "Controlled handoff", text: "Delivery status and proof stay linked to the order." }, { icon: ShieldCheck, label: "Customer recourse", text: "Quality reports connect back to the original lot." }].map(({ icon: Icon, label, text }, index) => <div key={label} className="grid grid-cols-[36px_1fr_auto] gap-3 border-b border-border py-4"><Icon className="size-4 text-primary" /><div><p className="text-xs font-bold text-ink">{label}</p><p className="mt-1 text-[10px] text-muted-foreground">{text}</p></div><span className="font-mono text-[9px] text-muted-foreground">0{index + 1}</span></div>)}</div></MarketSection></div>
    <MarketSection className="flex flex-col gap-6 py-14 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-heading text-4xl font-semibold text-ink">Ready to inspect today’s catch?</h2><p className="mt-3 text-sm text-muted-foreground">Start with evidence, then choose the fish.</p></div><div className="flex flex-wrap gap-2"><Link href="/shop" className="inline-flex h-11 items-center gap-2 rounded-md bg-primary px-5 text-sm font-bold text-primary-foreground">Browse the market <ArrowRight className="size-4" /></Link><Link href="/seller/onboarding" className="inline-flex h-11 items-center gap-2 rounded-md border border-border bg-surface px-5 text-sm font-bold text-ink">Become a seller</Link></div></MarketSection>
  </>;
}
