"use client";

import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ArrowLeft, ArrowRight, Check, CreditCard, MapPin, PackageCheck, ShieldCheck, Tag, Truck } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

const steps = ["Contact", "Address", "Delivery", "Substitution", "Payment", "Review"] as const;

export function CheckoutWizard() {
  const [step, setStep] = useState(0);
  const [slot, setSlot] = useState("Today · 6:00–8:00 PM");
  const [payment, setPayment] = useState("Cash on delivery");
  const [substitution, setSubstitution] = useState(false);
  const [terms, setTerms] = useState(false);

  const fieldClass = "h-11 rounded-md bg-surface";
  return (
    <div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-10 lg:py-12 xl:px-0">
      <ol className="mb-8 grid grid-cols-3 gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-6" aria-label="Checkout progress">{steps.map((label, index) => <li key={label}><button type="button" onClick={() => index <= step && setStep(index)} className={`flex h-14 w-full items-center gap-2 px-3 text-left ${index === step ? "bg-primary text-primary-foreground" : index < step ? "bg-primary-soft text-primary" : "bg-surface text-muted-foreground"}`}><span className={`flex size-5 shrink-0 items-center justify-center rounded-md border text-[9px] font-bold ${index < step ? "border-primary bg-primary text-primary-foreground" : "border-current/25"}`}>{index < step ? <Check className="size-3" /> : index + 1}</span><span className="hidden text-[10px] font-bold sm:block">{label}</span></button></li>)}</ol>

      <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_360px]">
        <section className="rounded-lg border border-border bg-surface p-5 sm:p-7" aria-labelledby="checkout-step-title">
          <p className="text-[10px] font-bold text-primary uppercase">Step {step + 1} of 6</p><h2 id="checkout-step-title" className="mt-2 font-heading text-3xl font-semibold text-ink">{steps[step]}</h2>
          <div className="mt-7 min-h-72">
            {step === 0 ? <div className="grid gap-5 sm:grid-cols-2"><div><Label htmlFor="name">Full name</Label><Input id="name" defaultValue="Nadia Rahman" className={`mt-2 ${fieldClass}`} /></div><div><Label htmlFor="phone">Phone number</Label><Input id="phone" defaultValue="+880 17 0000 0000" className={`mt-2 ${fieldClass}`} /></div><div className="sm:col-span-2"><Label htmlFor="email">Email address</Label><Input id="email" type="email" defaultValue="nadia@example.com" className={`mt-2 ${fieldClass}`} /></div></div> : null}
            {step === 1 ? <div className="grid gap-5 sm:grid-cols-2"><div><Label htmlFor="division">Division</Label><Input id="division" defaultValue="Dhaka" className={`mt-2 ${fieldClass}`} /></div><div><Label htmlFor="district">District</Label><Input id="district" defaultValue="Dhaka" className={`mt-2 ${fieldClass}`} /></div><div><Label htmlFor="area">Area</Label><Input id="area" placeholder="Dhanmondi" className={`mt-2 ${fieldClass}`} /></div><div><Label htmlFor="label">Address label</Label><Input id="label" placeholder="Home" className={`mt-2 ${fieldClass}`} /></div><div className="sm:col-span-2"><Label htmlFor="details">House, road, and delivery details</Label><Input id="details" placeholder="House 12, Road 7" className={`mt-2 ${fieldClass}`} /></div><p className="flex items-center gap-2 text-xs text-primary sm:col-span-2"><MapPin className="size-4" /> This address is inside the active Dhaka delivery zone.</p></div> : null}
            {step === 2 ? <div><p className="text-sm text-muted-foreground">Choose one server-confirmed slot. Capacity updates as orders are placed.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{["Today · 6:00–8:00 PM", "Today · 8:00–10:00 PM", "Tomorrow · 9:00–11:00 AM", "Tomorrow · 11:00 AM–1:00 PM"].map((value) => <button key={value} type="button" onClick={() => setSlot(value)} className={`flex min-h-16 items-center gap-3 rounded-lg border p-4 text-left text-xs font-bold ${slot === value ? "border-primary bg-primary-soft text-primary" : "border-border hover:border-primary/45"}`}><Truck className="size-4" /> {value}{slot === value ? <Check className="ml-auto size-4" /> : null}</button>)}</div></div> : null}
            {step === 3 ? <div><label className="flex cursor-pointer items-start gap-3 rounded-lg border border-border bg-surface-muted p-5"><Checkbox checked={substitution} onCheckedChange={(value) => setSubstitution(Boolean(value))} className="mt-0.5" /><span><span className="block text-sm font-bold text-ink">Allow verified substitutions</span><span className="mt-2 block text-xs leading-5 text-muted-foreground">A seller may suggest the same species and preparation from another verified lot. You must approve changes above 10% in weight or price.</span></span></label><div className="mt-4 border-l-2 border-coral pl-4 text-xs leading-5 text-muted-foreground">No substitution happens silently. Your consent and the replacement lot passport remain attached to the order.</div></div> : null}
            {step === 4 ? <div><p className="text-sm text-muted-foreground">Select a payment method for the server-confirmed estimate.</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{["Cash on delivery", "bKash", "Card"].map((value) => <button key={value} type="button" onClick={() => setPayment(value)} className={`min-h-20 rounded-lg border p-4 text-left ${payment === value ? "border-action bg-action/8 text-action" : "border-border"}`}><CreditCard className="size-4" /><span className="mt-3 block text-xs font-bold">{value}</span></button>)}</div></div> : null}
            {step === 5 ? <div className="space-y-5"><div className="grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2">{[["Contact", "Nadia Rahman · +880 17 0000 0000"], ["Address", "Dhanmondi, Dhaka"], ["Delivery", slot], ["Payment", payment], ["Substitution", substitution ? "Allowed with approval rules" : "Not allowed"], ["Final estimate rule", "Packed verified weight applies"]].map(([label, value]) => <div key={label} className="bg-surface-muted p-4"><p className="text-[9px] font-bold text-muted-foreground uppercase">{label}</p><p className="mt-1 text-xs font-bold text-ink">{value}</p></div>)}</div><label className="flex cursor-pointer items-start gap-3"><Checkbox checked={terms} onCheckedChange={(value) => setTerms(Boolean(value))} className="mt-0.5" /><span className="text-xs leading-5 text-muted-foreground">I agree to the <Link href="/policies/terms" className="font-bold text-primary">Terms</Link>, estimated-weight rule, and quality policy.</span></label></div> : null}
          </div>

          <div className="mt-7 flex items-center justify-between border-t border-border pt-5"><Button type="button" variant="ghost" className="rounded-md" disabled={step === 0} onClick={() => setStep((value) => Math.max(0, value - 1))}><ArrowLeft className="size-4" /> Back</Button>{step < 5 ? <Button type="button" className="rounded-md" onClick={() => setStep((value) => Math.min(5, value + 1))}>Continue <ArrowRight className="size-4" /></Button> : <Button render={<Link href="/order/success" />} nativeButton={false} disabled={!terms} className="rounded-md bg-coral text-white hover:bg-coral/88"><PackageCheck className="size-4" /> Place order</Button>}</div>
        </section>

        <aside className="lg:sticky lg:top-24 lg:self-start"><div className="rounded-lg border border-border bg-market-rail p-5 text-market-rail-ink"><div className="flex items-center justify-between"><h2 className="text-sm font-bold">Server estimate</h2><span className="flex items-center gap-1 text-[9px] font-bold text-market-aqua uppercase"><ShieldCheck className="size-3.5" /> Recalculated</span></div><div className="mt-5 space-y-4 border-y border-market-rail-ink/14 py-5">{[["Mawa River Collective", "2 items · ৳3,415"], ["Shyamnagar Aquatics", "1 item · unavailable"]].map(([seller, detail]) => <div key={seller}><p className="text-xs font-bold">{seller}</p><p className="mt-1 text-[10px] text-market-rail-ink/55">{detail}</p></div>)}</div><dl className="space-y-3 py-5 text-xs"><div className="flex justify-between"><dt className="text-market-rail-ink/55">Items</dt><dd>৳3,415</dd></div><div className="flex justify-between"><dt className="text-market-rail-ink/55">Delivery allocation</dt><dd>৳180</dd></div><div className="flex justify-between"><dt className="text-market-rail-ink/55">Service fee</dt><dd>৳45</dd></div></dl><div className="flex items-end justify-between border-t border-market-rail-ink/14 pt-4"><div><p className="text-[9px] font-bold text-market-rail-ink/45 uppercase">Final estimate</p><p className="mt-1 text-[9px] text-market-rail-ink/45">Before packed weight</p></div><p className="font-heading text-3xl font-semibold">৳3,640</p></div></div><div className="mt-4 flex h-11 items-center rounded-lg border border-border bg-surface px-3"><Tag className="size-4 text-coral" /><input placeholder="Coupon code" className="min-w-0 flex-1 bg-transparent px-2 text-xs outline-none" /><Button type="button" variant="ghost" size="sm" className="rounded-md">Apply</Button></div></aside>
      </div>
    </div>
  );
}
