import { MarketPageHeader, MarketSection } from "@/components/marketplace/page-shell";
import { ArrowRight, HelpCircle, MessageCircle } from "lucide-react";
import Link from "next/link";

const faqGroups = [
  { title: "Buying and weight", items: [["Why is my cart total an estimate?", "Fish is sold by packed weight. The server recalculates inventory, preparation charges, fees, and the final packed-weight amount before invoicing."], ["Can packed weight differ from requested weight?", "Yes. Natural fish sizes vary. The order shows requested and packed weight separately, and approval rules apply when the difference exceeds the configured tolerance."], ["What preparation options are available?", "Available options depend on the product and seller. Common choices are whole, cleaned, steaks, and fillet, each with a probable edible-yield range."]] },
  { title: "Freshness and trace", items: [["What does inspector verified mean?", "A designated inspector recorded required quality checks and public evidence for the lot. The claim is shown with text and an icon, not color alone."], ["Can a seller change old trace events?", "No. Trace history follows an append-only principle. A correction adds a new event and leaves the original record visible."], ["Why do some products have different evidence levels?", "Source records, weight evidence, inspection, and cold-handling data may be completed at different levels. The product and trace pages show what is actually available."]] },
  { title: "Delivery, refunds, and account", items: [["How are multiple sellers delivered?", "The checkout shows seller splits and allocates delivery fees. Fulfillment may be separate even when the final handoff is coordinated."], ["What if the delivered fish has a quality issue?", "Report the issue within the stated quality window, attach clear evidence, and keep the package label or lot code. Operations reviews the order and trace record."], ["Is private seller identity data public?", "No. Public storefronts show verification status and performance, but private KYC documents are never published."]] },
];

export function FaqPage() { return <><MarketPageHeader eyebrow="Help center" title="Questions, answered clearly" description="Practical guidance on weight, evidence, delivery, refunds, and account safety." breadcrumbs={[{ label: "FAQ" }]} /><MarketSection className="grid gap-10 py-12 lg:grid-cols-[230px_1fr] lg:py-16"><aside><div className="sticky top-24"><HelpCircle className="size-7 text-primary" /><p className="mt-5 text-sm leading-6 text-muted-foreground">Could not find the answer you need?</p><Link href="/contact" className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-primary"><MessageCircle className="size-4" /> Contact support</Link></div></aside><div className="space-y-10">{faqGroups.map((group) => <section key={group.title}><h2 className="font-heading text-3xl font-semibold text-ink">{group.title}</h2><div className="mt-5 divide-y divide-border border-y border-border">{group.items.map(([question, answer]) => <details key={question} className="group"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 py-4 text-sm font-bold text-ink">{question}<span className="flex size-7 shrink-0 items-center justify-center rounded-md bg-primary-soft text-primary transition-transform group-open:rotate-45">+</span></summary><p className="max-w-3xl pb-5 pr-10 text-xs leading-6 text-muted-foreground">{answer}</p></details>)}</div></section>)}</div></MarketSection><div className="border-t border-border bg-surface"><MarketSection className="flex flex-col gap-5 py-10 sm:flex-row sm:items-center sm:justify-between"><p className="font-heading text-2xl font-semibold text-ink">Still need a human answer?</p><Link href="/contact" className="inline-flex items-center gap-2 text-sm font-bold text-primary">Open contact page <ArrowRight className="size-4" /></Link></MarketSection></div></>; }
