import { MarketPageHeader, MarketSection, SectionTitle, StatusBadge } from "@/components/marketplace/page-shell";
import { BadgeCheck, Check, Clock3, CreditCard, FileCheck2, MapPin, PackageCheck, Scale, ShieldCheck, Truck } from "lucide-react";
import Link from "next/link";

export function OrderDetail({ orderNo }: { orderNo: string }) {
  const timeline = [
    { title: "Order placed", detail: "Server estimate accepted", time: "10:42 AM", complete: true, icon: Check },
    { title: "Seller accepted", detail: "All available items confirmed", time: "10:49 AM", complete: true, icon: BadgeCheck },
    { title: "Packed weight recorded", detail: "Final invoice pending evidence review", time: "11:28 AM", complete: true, icon: Scale },
    { title: "Ready for delivery", detail: "Pickup handoff is next", time: "Expected 2:30 PM", complete: false, icon: PackageCheck },
    { title: "Delivered", detail: "Customer OTP required", time: "Today · 6–8 PM", complete: false, icon: Truck },
  ];

  return (
    <>
      <MarketPageHeader eyebrow="Order tracking" title={`Order ${orderNo}`} description="Seller fulfillment, packed weight, payment, delivery proof, and trace links in one record." breadcrumbs={[{ label: "Orders", href: "/account/orders" }, { label: orderNo }]} action={<StatusBadge icon={Clock3} tone="warning">Preparing</StatusBadge>} />
      <MarketSection className="grid gap-8 py-8 lg:grid-cols-[minmax(0,1fr)_350px] lg:py-12">
        <div className="space-y-8">
          <section className="rounded-lg border border-border bg-surface p-5 sm:p-7"><SectionTitle eyebrow="Parent order timeline" title="From acceptance to delivery" /><div className="mt-7 border-t border-border">{timeline.map(({ title, detail, time, complete, icon: Icon }) => <div key={title} className="grid grid-cols-[36px_1fr_auto] gap-3 border-b border-border py-4"><span className={`flex size-8 items-center justify-center rounded-md ${complete ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}><Icon className="size-4" /></span><div><p className="text-xs font-bold text-ink">{title}</p><p className="mt-1 text-[10px] text-muted-foreground">{detail}</p></div><time className="text-right font-mono text-[9px] text-muted-foreground">{time}</time></div>)}</div></section>
          <section className="rounded-lg border border-border bg-surface"><header className="border-b border-border p-5"><p className="flex items-center gap-2 text-xs font-bold text-ink"><BadgeCheck className="size-4 text-primary" /> Mawa River Collective</p><p className="mt-1 text-[10px] text-muted-foreground">Seller order MB-SO-1842-A · Preparing</p></header><div className="grid gap-px bg-border sm:grid-cols-3">{[["Item", "Padma Hilsa · Steaks"], ["Requested", "1.5 kg"], ["Packed", "1.42 kg"]].map(([label, value]) => <div key={label} className="bg-surface p-4"><p className="text-[9px] font-bold text-muted-foreground uppercase">{label}</p><p className="mt-1 text-xs font-bold text-ink">{value}</p></div>)}</div><div className="flex flex-wrap gap-3 border-t border-border p-4"><Link href="/trace/MB-PD-0716-04" className="inline-flex items-center gap-2 text-xs font-bold text-primary"><FileCheck2 className="size-4" /> Open catch passport</Link><span className="text-[10px] text-muted-foreground">Preparation yield: 78–84%</span></div></section>
          <section className="grid gap-4 sm:grid-cols-2"><div className="rounded-lg border border-border bg-surface p-5"><p className="flex items-center gap-2 text-xs font-bold text-ink"><MapPin className="size-4 text-coral" /> Delivery address</p><p className="mt-4 text-xs leading-5 text-muted-foreground">Home · Dhanmondi, Dhaka<br />House 12, Road 7</p><p className="mt-3 text-[10px] font-bold text-primary">Today · 6:00–8:00 PM</p></div><div className="rounded-lg border border-border bg-surface p-5"><p className="flex items-center gap-2 text-xs font-bold text-ink"><ShieldCheck className="size-4 text-primary" /> Delivery proof</p><p className="mt-4 text-xs leading-5 text-muted-foreground">Customer OTP will appear when the order is out for delivery. Contact details remain masked until handoff.</p><p className="mt-3 text-[10px] font-bold text-warning">OTP not issued yet</p></div></section>
        </div>
        <aside className="lg:sticky lg:top-24 lg:self-start"><div className="rounded-lg border border-border bg-market-rail p-5 text-market-rail-ink"><p className="flex items-center gap-2 text-xs font-bold"><CreditCard className="size-4 text-market-aqua" /> Final invoice</p><dl className="mt-5 space-y-3 border-y border-market-rail-ink/14 py-5 text-xs"><div className="flex justify-between"><dt className="text-market-rail-ink/55">Items after packed weight</dt><dd>৳3,267</dd></div><div className="flex justify-between"><dt className="text-market-rail-ink/55">Preparation</dt><dd>৳120</dd></div><div className="flex justify-between"><dt className="text-market-rail-ink/55">Delivery and service</dt><dd>৳315</dd></div><div className="flex justify-between"><dt className="text-market-rail-ink/55">Refund/credit</dt><dd>৳0</dd></div></dl><div className="flex items-end justify-between pt-5"><div><p className="text-[9px] text-market-rail-ink/45 uppercase">Final payable</p><p className="mt-1 text-[9px] text-market-rail-ink/45">Cash on delivery</p></div><p className="font-heading text-3xl font-semibold">৳3,702</p></div></div><div className="mt-4 grid gap-2"><Link href="/contact" className="inline-flex h-10 items-center justify-center rounded-md border border-border bg-surface text-xs font-bold text-ink">Report an issue</Link><button type="button" disabled className="h-10 rounded-md bg-muted text-xs font-bold text-muted-foreground">Cancellation window closed</button></div></aside>
      </MarketSection>
    </>
  );
}
