import { MarketPageHeader, MarketSection } from "@/components/marketplace/page-shell";
import { FileText, Mail, ShieldCheck } from "lucide-react";
import Link from "next/link";

type PolicySection = { title: string; body: string; bullets?: string[] };
type Policy = { title: string; eyebrow: string; description: string; updated: string; sections: PolicySection[] };

export const policies: Record<string, Policy> = {
  privacy: { title: "Privacy Policy", eyebrow: "Data and privacy", description: "How Machh Bazar collects, uses, protects, and limits access to personal data.", updated: "16 July 2026", sections: [
    { title: "Information we collect", body: "We collect information needed to create accounts, fulfill orders, prevent abuse, support disputes, and improve marketplace reliability.", bullets: ["Name, email, phone, and authentication records", "Delivery addresses and optional map coordinates", "Order, payment-status, refund, and support history", "Device, request, and security logs where appropriate"] },
    { title: "How we use information", body: "Personal information is used to provide the requested marketplace service, calculate delivery feasibility, communicate order changes, secure accounts, and comply with legal obligations." },
    { title: "Public trace records", body: "Public catch passports may show lot, species, origin, seller storefront, evidence, and correction events. They do not publish customer identity, private seller KYC documents, passwords, tokens, or payment secrets." },
    { title: "Sharing and processors", body: "We share only the information required by verified sellers, delivery providers, payment processors, and support operators to perform their role. Customer contact may be masked where practical." },
    { title: "Retention and security", body: "Records are retained for operational, dispute, accounting, and legal periods. Access is role-limited and sensitive values are excluded from audit snapshots." },
    { title: "Your choices", body: "You may request profile correction, account data export, notification changes, or account deletion, subject to records that must be retained for fraud, dispute, or legal reasons." },
  ] },
  terms: { title: "Terms of Service", eyebrow: "Marketplace agreement", description: "The rules that govern accounts, estimates, orders, payments, seller activity, and acceptable use.", updated: "16 July 2026", sections: [
    { title: "Marketplace role", body: "Machh Bazar provides a marketplace and operational record system connecting customers with independent verified sellers. Seller identity and performance are reviewed, but availability remains lot-based." },
    { title: "Accounts and security", body: "You must provide accurate information, protect account credentials, and notify us of suspected unauthorized access. We may rate-limit, suspend, or require secure verification when risk is detected." },
    { title: "Estimated weight and final price", body: "Fish weight may vary naturally. Product, cart, and checkout totals are estimates until the server confirms inventory, packed weight, preparation charges, fees, discounts, and payment status.", bullets: ["Requested and packed weight are displayed separately", "Configured approval rules apply to material changes", "The server-calculated invoice is the final source of truth"] },
    { title: "Orders, delivery, and substitution", body: "Orders may split by seller. Delivery slots depend on zone capacity. A substitution is allowed only under the consent and tolerance settings shown at checkout." },
    { title: "Payments, cancellations, and refunds", body: "Supported payment methods and cancellation eligibility are shown before confirmation. Refunds follow the Refund Policy and may return to the original method or approved wallet credit." },
    { title: "Acceptable use", body: "Users may not manipulate reviews, falsify evidence, interfere with trace records, abuse refund processes, scrape private data, or attempt invalid order-state transitions." },
  ] },
  refund: { title: "Refund and Quality Policy", eyebrow: "Customer recourse", description: "What to report, what evidence helps, and how quality, weight, delivery, and availability issues are resolved.", updated: "16 July 2026", sections: [
    { title: "Eligible issues", body: "A case may be reviewed when the delivered item materially differs from the confirmed order or documented quality standard.", bullets: ["Verified spoilage or unacceptable quality at delivery", "Wrong species, cut, or seller item", "Material packed-weight or invoice mismatch", "Missing item, failed delivery, or unauthorized substitution"] },
    { title: "Report window", body: "Quality issues should be reported as soon as possible and within the window shown on the order, normally two hours after delivery. Missing-item or payment issues should be reported within 24 hours." },
    { title: "Evidence", body: "Include the order number, lot or package label, clear photographs, and a concise description. Keep packaging until the case is acknowledged when practical." },
    { title: "Weight disputes", body: "We compare requested weight, seller packed weight, scale evidence, probable preparation yield, and the final invoice. Normal cut yield is not treated as missing whole-fish weight." },
    { title: "Possible resolutions", body: "Depending on evidence and availability, a case may result in replacement, partial refund, full refund, approved wallet credit, or denial with an explanation." },
    { title: "Refund timing", body: "Approved refunds are initiated after review. Bank and payment-provider settlement times vary. The case page shows the amount, method, status, and expected SLA." },
  ] },
};

export function PolicyPage({ policyKey }: { policyKey: string }) {
  const policy = policies[policyKey] ?? policies.terms;
  return <><MarketPageHeader eyebrow={policy.eyebrow} title={policy.title} description={policy.description} breadcrumbs={[{ label: "Policies" }, { label: policy.title }]} /><MarketSection className="grid gap-10 py-12 lg:grid-cols-[230px_1fr] lg:py-16"><aside><div className="sticky top-24"><FileText className="size-6 text-primary" /><p className="mt-4 text-[10px] font-bold text-muted-foreground uppercase">Last updated</p><p className="mt-1 text-xs font-bold text-ink">{policy.updated}</p><nav className="mt-6 border-t border-border pt-4" aria-label="Policy navigation">{Object.entries(policies).map(([key, item]) => <Link key={key} href={`/policies/${key}`} className={`block border-b border-border py-3 text-xs font-bold ${key === policyKey ? "text-primary" : "text-muted-foreground hover:text-ink"}`}>{item.title}</Link>)}</nav></div></aside><article className="max-w-3xl"><div className="mb-8 flex items-start gap-3 rounded-lg border border-primary/20 bg-primary-soft p-4"><ShieldCheck className="size-5 shrink-0 text-primary" /><p className="text-xs leading-5 text-muted-foreground">This page is written for practical product use and portfolio demonstration. Local legal review is required before production launch.</p></div><div className="space-y-10">{policy.sections.map((section, index) => <section key={section.title} id={`section-${index + 1}`}><p className="font-mono text-[9px] font-bold text-primary">0{index + 1}</p><h2 className="mt-2 font-heading text-3xl font-semibold text-ink">{section.title}</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">{section.body}</p>{section.bullets ? <ul className="mt-4 space-y-2 border-l-2 border-coral pl-4">{section.bullets.map((bullet) => <li key={bullet} className="text-xs leading-5 text-muted-foreground">{bullet}</li>)}</ul> : null}</section>)}</div><div className="mt-12 flex items-start gap-3 border-t border-border pt-6"><Mail className="size-4 shrink-0 text-primary" /><p className="text-xs text-muted-foreground">Questions about this policy? <Link href="/contact" className="font-bold text-primary">Contact support</Link>.</p></div></article></MarketSection></>;
}
