import { allProducts, getRecipe, recipes } from "@/components/marketplace/market-data";
import { MarketPageHeader, MarketSection, SectionTitle } from "@/components/marketplace/page-shell";
import { ArrowRight, ChefHat, Check, Clock3, Flame, Scale, ShoppingBag, Users } from "lucide-react";
import Image from "next/image";
import Link from "next/link";

export function RecipeDetail({ slug }: { slug: string }) {
  const recipe = getRecipe(slug);
  const ingredients = ["1 kg fresh fish, cleaned", "3 tbsp mustard paste", "1 tsp turmeric", "4 green chillies", "3 tbsp mustard oil", "Salt to taste"];
  const steps = ["Pat the prepared fish dry and season with salt and turmeric.", "Whisk mustard paste with water until smooth, then strain if needed.", "Heat mustard oil, add chillies, and place the fish in a single layer.", "Pour over the mustard sauce, cover, and cook gently until the fish is just done.", "Rest for five minutes before serving with steamed rice."];
  return (
    <>
      <MarketPageHeader eyebrow="Market kitchen" title={recipe.title} description={recipe.description} breadcrumbs={[{ label: "Recipes", href: "/recipes" }, { label: recipe.title }]} />
      <MarketSection className="py-8 lg:py-12"><div className="relative min-h-[440px] overflow-hidden rounded-lg border border-border sm:min-h-[620px]"><Image src={recipe.image} alt={`${recipe.title} ready to serve`} fill priority sizes="100vw" className="object-cover" /><div className="absolute right-4 bottom-4 left-4 grid grid-cols-3 gap-px overflow-hidden rounded-lg bg-white/18 backdrop-blur sm:right-8 sm:bottom-8 sm:left-auto sm:w-[430px]">{[{ icon: Clock3, label: "Time", value: recipe.time }, { icon: ChefHat, label: "Level", value: recipe.difficulty }, { icon: Users, label: "Serves", value: "4 people" }].map(({ icon: Icon, label, value }) => <div key={label} className="bg-market-rail/92 p-3 text-market-rail-ink"><Icon className="size-4 text-coral" /><p className="mt-2 text-[9px] text-market-rail-ink/50 uppercase">{label}</p><p className="mt-1 text-xs font-bold">{value}</p></div>)}</div></div></MarketSection>

      <MarketSection className="grid gap-12 py-16 lg:grid-cols-[0.78fr_1.22fr] lg:py-20"><aside><div className="lg:sticky lg:top-24"><SectionTitle eyebrow="Before you start" title="Ingredients" /><ul className="mt-6 divide-y divide-border border-y border-border">{ingredients.map((ingredient) => <li key={ingredient} className="flex items-center gap-3 py-3 text-xs text-ink"><Check className="size-3.5 text-primary" /> {ingredient}</li>)}</ul><div className="mt-6 rounded-lg border border-primary/20 bg-primary-soft p-4"><p className="text-[10px] font-bold text-primary uppercase">Best fish match</p><p className="mt-2 text-sm font-bold text-ink">{recipe.fish}</p><p className="mt-2 text-[10px] leading-5 text-muted-foreground">Ask for cleaned preparation to reduce prep time.</p><Link href={`/fish/${allProducts[0].slug}`} className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-primary"><ShoppingBag className="size-3.5" /> Shop this fish</Link></div></div></aside><div><SectionTitle eyebrow="Method" title="Cook with restraint" description="Keep the heat gentle so the fish stays moist and the mustard remains bright." /><ol className="mt-8 border-t border-border">{steps.map((step, index) => <li key={step} className="grid grid-cols-[40px_1fr] gap-4 border-b border-border py-5"><span className={`flex size-9 items-center justify-center rounded-md font-mono text-[10px] font-bold ${index === 0 ? "bg-coral text-white" : "bg-primary-soft text-primary"}`}>0{index + 1}</span><p className="pt-1 text-sm leading-6 text-muted-foreground">{step}</p></li>)}</ol><div className="mt-8 grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-3">{[["Per serving", "420 kcal"], ["Protein", "34 g"], ["Active cook", "22 min"]].map(([label, value]) => <div key={label} className="bg-surface p-4"><p className="text-[9px] font-bold text-muted-foreground uppercase">{label}</p><p className="mt-1 text-sm font-bold text-ink">{value}</p></div>)}</div></div></MarketSection>

      <div className="border-y border-border bg-market-rail text-market-rail-ink"><MarketSection className="flex flex-col gap-6 py-10 sm:flex-row sm:items-center sm:justify-between"><div><p className="flex items-center gap-2 text-[10px] font-bold text-market-aqua uppercase"><Flame className="size-4" /> Cook note</p><p className="mt-3 max-w-2xl font-heading text-2xl leading-8">Exact cooking time changes with cut thickness. Stop when the flesh separates cleanly but still looks moist.</p></div><Scale className="size-8 shrink-0 text-coral" /></MarketSection></div>

      <MarketSection className="py-16"><div className="flex items-end justify-between"><SectionTitle eyebrow="Keep cooking" title="Related recipes" /><Link href="/recipes" className="text-xs font-bold text-primary">All recipes</Link></div><div className="mt-8 grid gap-5 sm:grid-cols-2">{recipes.filter((item) => item.slug !== recipe.slug).slice(0, 2).map((item) => <Link key={item.slug} href={`/recipes/${item.slug}`} className="group grid min-h-52 grid-cols-[150px_1fr] overflow-hidden rounded-lg border border-border bg-surface"><span className="relative"><Image src={item.image} alt={item.title} fill sizes="150px" className="object-cover" /></span><span className="flex flex-col justify-center p-5"><span className="text-[9px] font-bold text-primary uppercase">{item.time} · {item.difficulty}</span><span className="mt-3 font-heading text-2xl font-semibold text-ink group-hover:text-primary">{item.title}</span><span className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-primary">Open recipe <ArrowRight className="size-3.5" /></span></span></Link>)}</div></MarketSection>
    </>
  );
}
